config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  
  resources :users do
    collection do
      get :list, :customer
    end
  end
  
  resources :books do
    collection do
      get :list, :export
      post :returned, :import, :checkout
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/audio_book.rb
class AudioBook < Book
end

app/models/book.rb
require 'csv'

class Book < ApplicationRecord
  has_many :customer_books, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :customers, -> { order(created_at: :desc) }, through: :customer_books
  
  RETURNED_STATUS = 'returned'
  CHECKED_OUT_STATUS = 'checked out'
  AVAILABLE_STATUS = 'available'

  def self.available_books
    Book.where.not(id: CustomerBook.select(:book_id).where(status: CHECKED_OUT_STATUS))
  end

  def self.return_book(book_id, customer_id)
    customer_book = CustomerBook.find_by(book_id: book_id, customer_id: customer_id)

    return { success: false, message: "Customer does not have that book." } unless customer_book

    customer_book.status = RETURNED_STATUS
    
    if customer_book.save
      return { success: true, message: "Book has been marked as returned." }
    else
      return { success: false, message: "Book could not be marked as returned." }
    end
  end

  def self.checkout_book(book_id, customer_id)
    @customer = Customer.find_customer(customer_id)
    book = CustomerBook.find_or_initialize_by(book_id: book_id, customer_id: customer_id)
    book.status = CHECKED_OUT_STATUS

    if book.save
      return { success: true, message: "Book has been checked out." }
    else
      return { success: false, message: "Book could not be checked out." }
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: :true) do |row|
      book = Book.find_or_initialize_by(isbn: row["isbn"])
      book.update(row.to_hash)
    end 
  end

  def self.export_all
    headers = %w{isbn title author category type rentee status last_activity_at}

    CSV.generate(headers: true) do |csv|
      csv << headers

      Book.find_each do |book|
        cb = book.customer_books&.first
        status = cb&.status || AVAILABLE_STATUS
        last_activity_at = cb&.updated_at || ''
        customer = cb&.customer
        rentee = customer ? "#{customer.first_name} #{customer.last_name}" : ''

        row = [
          book.isbn,
          book.title,
          book.author,
          book.category,
          book[:type],
          rentee,
          status,
          last_activity_at
        ]

        csv << row
      end
    end
  end

  def self.order_by_latest
    Book.order("created_at DESC")
  end
end

app/models/customer.rb
class Customer < User
  has_many :customer_books, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :books, -> { order(created_at: :desc) }, through: :customer_books
  has_many :audio_books, -> { where(type: "AudioBook") }, through: :customer_books, source: :book
  has_many :physical_books, -> { where(type: "PhysicalBook") }, through: :customer_books, source: :book
  
    def self.find_customer(customer_id)
      Customer.where(["id = ?", customer_id]).first
    end
end
  

app/models/customer_book.rb
class CustomerBook < ApplicationRecord
  belongs_to :customer, optional: true
  belongs_to :book, optional: true
  
  def self.find_customers_books(book, customer)
    CustomerBook.where(["book_id = ? and customer_id = ?", book, customer]).first
  end
end

app/models/librarian.rb
class Librarian < User
end

app/models/physical_book.rb
class PhysicalBook < Book
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end
  
  def list
    @customer = Customer.find_customer(params[:customer_id])
    @customer_books = @customer.customer_books
  end
  
  def returned
    result = Book.return_book(book_id = params[:id], customer_id = params[:customer_id])

    if result[:success]
      flash[:success] = result[:message]
    else
      flash[:error] = result[:message]
    end

    redirect_to list_books_path(customer_id: params[:customer_id])
  end

  def checkout
    result = Book.checkout_book(params[:book_id], params[:customer_id])

    if result[:success]
      flash[:success] = result[:message]
    else
      flash[:error] = result[:message]
    end

    redirect_back(fallback_location: user_path(params[:customer_id]))
  end

  def import
    Book.import(params[:file])
    redirect_to books_path, notice: "New Books Added!"
  end

  def export
    csv = Book.export_all
    filename = "books-#{Date.today}.csv"
    bom = "\uFEFF"
    send_data bom + csv, filename: filename, type: 'text/csv; charset=utf-8', disposition: 'attachment'
  end

  def index
    @books = Book.order_by_latest
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def customer
    @customers = Customer.all
  end
  
  def list
    @customers = Customer.all
  end
  
  def show
    @customer = Customer.find_customer(params[:id])
    @customer_books = @customer.customer_books
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  include ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  include ApplicationHelper
  
  def total_book_count(customer)
    books = CustomerBook.where("customer_id = #{customer.id}")
    books.size
  end

  def current_checked_out_books(customer)
    books = CustomerBook.where("customer_id = #{customer.id} AND status = '#{Book::CHECKED_OUT_STATUS}'")
    books.size
  end

  def physical_books(customer)
    customer.books.where(["type = ?", "PhysicalBook"]).count
  end

  def audio_books(customer)
    customer.books.where(["type = ?", "AudioBook"]).count
  end
end

app/views/books/_available_books_table.erb
<div id="featureWrap" class="floatLeft reports">
  	<h2>Available Books</h2>
  
  	<table class="report" cellpadding="0" cellspacing="0">
  		<tr>
        <th>Title</th>
        <th>Author</th>
        <th>Genre</th>
        <th>Checkout</th>
  		</tr>
  		<% Book.available_books.each do |book| -%>
  			<tr class="<%= cycle("rowA", "rowB") -%>">
          <td><%= book.title %></td>
          <td><%= book.author %></td>
          <td><%= book.category %></td>
          <td>
            <%= form_tag(checkout_books_path) do %>
              <%= hidden_field_tag :customer_id, @customer.id %>
              <%= hidden_field_tag :book_id, book.id %>
              <%= image_submit_tag("btn_reviewed.png", alt: "CHECKOUT", title: "CHECKOUT", data: { turbo: false }) %>
            <% end %>
          </td>
        </tr>
      <% end -%>
    </table>
		
  </div>
  

app/views/books/_customer_books_table.erb
<div id="featureWrap" class="floatLeft reports">
  	<h2>My Books</h2>
  
  	<table class="report" cellpadding="0" cellspacing="0">
  		<tr>
        <th>Date</th>
        <th>Title</th>
        <th>Author</th>
        <th>Status</th>
        <% if as_librarian %>
          <th>Return</th>
        <% end %>
  		</tr>
     		<% customer_books.each do |customer_book| -%>
  			<tr class="<%= cycle("rowA", "rowB") -%>">
          <td><%= customer_book.created_at.to_date %></td>
          <td><%= customer_book.book.title %></td>
          <td><%= customer_book.book.author %></td>
          <td><%= customer_book.status %></td>
          <td>
            <% if customer_book.status == 'checked out' %>
    					<%= form_tag(returned_books_path) do %>
    						<%= hidden_field_tag :customer_id, customer.id %>
    						<%= hidden_field_tag :id, customer_book.book.id %>
                <% if as_librarian %>
    						  <%= image_submit_tag("btn_reviewed.png", alt: "RETURN", title: "RETURN", data: { turbo: false }) %>
                <% end %>
    					<% end %>
            <% end -%>
          </td>
        </tr>
      <% end -%>
    </table>
		
  </div>
  

app/views/books/_new.erb
<div>
  <div id="feature" class="floatLeft">
    <div id="featureHeading">
      <h1 class="floatLeft">Add New Books</h1>
      <div class="clear"></div>
    </div>

    <div style="margin-bottom: 20px;">
      <%= form_tag import_books_path, multipart: true%>
      <%= file_field_tag :file,
        id: "choose-csv-btn",
        accept: ".csv"
      %>
      <%= submit_tag "Import CSV",
        id: "import-csv-btn",
        disabled: true
      %>
    </div>
    <div>
      <p>
        <%= link_to 'Download CSV template', '/template.csv', download: 'template.csv', class: 'btn' %>
      </p>
    </div>
  </div>
</div>

app/views/books/index.erb
<div id="feature" class="floatLeft">
  <div id="featureHeading">
    <h1 class="floatLeft">Recently Added Books</h1>
    <div class="clear"></div>
  </div>
    <%= flash[:notice]%>

  <div id="featureWrap" class="floatLeft reports">  
    <table class="report" cellpadding="0" cellspacing="0">
  		<tr>
  			<th>Title</th>
  			<th>Author</th>
  			<th>Category</th>
  			<th>Type</th>
  			<th>Date Added</th>
  		</tr>
  		<% @books.each do |book| -%>
  		<tr class="<%= cycle("rowA", "rowB") -%>">
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.category %></td>
        <td><%= book.type %></td>
        <td><%= book.created_at.to_date %></td>
      </tr>
      <% end -%>
    </table>
  </div>
</div>

app/views/books/list.erb
<div id="feature" class="floatLeft">
  <div id="featureHeading">
    <h1 class="floatLeft">Books for <%= link_to "#{@customer.first_name} #{@customer.last_name}", user_path(@customer, view: 'librarian') %></h1>
    <div class="clear"></div>
  </div>
  
  <%= render partial: 'shared/flash' %>

  <%= render partial: 'books/customer_books_table', locals: { customer_books: @customer_books, customer: @customer, as_librarian: true } %>
</div>

app/views/books/new.erb
<script type="module">
  import "controllers/import_books";
</script>

<div>
  <div id="feature" class="floatLeft">
    <div id="featureHeading">
      <h1 class="floatLeft">Add New Books</h1>
      <div class="clear"></div>
    </div>

    <div style="margin-bottom: 20px;">
      <%= form_tag import_books_path, multipart: true%>
      <%= file_field_tag :file,
        id: "choose-csv-btn",
        accept: ".csv"
      %>
      <%= submit_tag "Import CSV",
        id: "import-csv-btn",
        disabled: true
      %>
    </div>
    <div>
      <p>
        <%= link_to 'Download CSV template', '/template.csv', download: 'template.csv', class: 'btn' %>
      </p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  <head>
    <title>LibraryApp</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_importmap_tags %>
    <%= csrf_meta_tags %>
  </head>

	<body>
		<%= render :partial => 'shared/header' %>
		
		<div id="container">
			<%= render :partial => 'shared/nav'%>
				
   		<%= yield %>

			<div class="clear"></div>
		</div>

	</body>
</html>

app/views/shared/_flash.erb
<% if !self.flash.empty? %>
  <% self.flash.keys.each do |msgtype| %>
    <div class="flash_<%= msgtype %>"><p><%= self.flash[msgtype.to_sym].html_safe %></p></div>
  <% end %>
<% end %>

app/views/shared/_header.erb
<!-- MASTHEAD -->
<div id="masthead">
  <div id="heading">
		Library Application
  </div>
</div>
<!-- End MASTHEAD -->

app/views/shared/_nav.erb
<!-- NAVIGATION -->
<div>
	<div id="nav">
    <ul>
      <%= content_tag(:li) do  %>
  			<%= link_to 'Librarian View', list_users_path %>
      <% end %>

      <%= content_tag(:li) do  %>
  			<%= link_to 'Customer View', customer_users_path %>
      <% end %>

      <%#= content_tag(:li) do %>
        <%#= link_to "Add New Books", new_book_path %>
      <%# end %>
    </ul>
  </div>
</div>
  

app/views/shared/_side_nav.erb
<!-- NAVIGATION -->
<div class="floatLeft">
	<div id="nav">
    <ul>
      <%= content_tag(:li) do  %>
  			<%= link_to 'Librarian View', list_users_path %>
      <% end %>

      <%= content_tag(:li) do  %>
  			<%= link_to 'Customer View', customer_users_path %>
      <% end %>

      <%= content_tag(:li) do %>
        <%= link_to "Add New Books", new_book_path %>
      <% end %>
    </ul>
  </div>
</div>
  

app/views/users/_show_as_customer.erb
<div id="feature" class="floatLeft">
  <div id="featureHeading">
    <h1 class="floatLeft">My Account Overview</h1>
    <div class="clear"></div>
  </div>
  
  <%= render partial: 'shared/flash' %>

  <div id="featureWrap" class="floatLeft reports">
  	<h2>Account Details</h2>
  
    <div class="summary floatLeft" style="padding-top: 0px;">
      <p>Name: <strong><%= "#{@customer.first_name} #{@customer.last_name}" %></strong></p>
      <p>Member Since: <strong><%= @customer.created_at.to_date %></strong></p>
    </div>
		
  </div>

  <%= render partial: 'books/customer_books_table', locals: { customer_books: @customer_books, customer: @customer, as_librarian: false } %>
  <%= render partial: 'books/available_books_table', locals: { customer: @customer } %>
</div>

app/views/users/_show_as_librarian.erb
<div id="feature" class="floatLeft">
  <div id="featureHeading">
    <h1 class="floatLeft">Customer : <%= "#{@customer.first_name} #{@customer.last_name}" %></h1>
    <div class="clear"></div>
  </div>


  <div id="featureWrap" class="floatLeft reports">
  	<h2>Account Details</h2>
  
    <div class="summary floatLeft" style="padding-top: 0px;">
      <p>First Name: <strong><%= @customer.first_name %></strong></p>
      <p>Last Name: <strong><%= @customer.last_name %></strong></p>
      <p>Member Date: <strong><%= @customer.created_at.to_date %></strong></p>
      <p>Total Books Checked Out: <strong><%= total_book_count(@customer) %></strong></p>
      <p>Books Currently Checked Out: <strong><%= current_checked_out_books(@customer) %></strong></p>
      <%= link_to "View Books", list_books_path(customer_id: @customer.id) %>

    </div>
		
  </div>

  <div>
    <h1 class="floatLeft">Customer List</h1>
    <%= render :partial => 'books/new' %>
  </div>
</div>

app/views/users/customer.erb
<div id="feature" class="floatLeft">
  <div id="featureHeading">
    <h1 class="floatLeft">"Login"</h1>
    <div class="clear"></div>
  </div>

  <div id="featureWrap" class="floatLeft reports">  
  	<table class="report" cellpadding="0" cellspacing="0">
  		<tr>
  			<th>Customer Name</th>
  			<th>Total Book Count</th>
        <th>Checked Out</th>
  		</tr>
  		<% @customers.each do |customer| -%>
  			<tr class="<%= cycle("rowA", "rowB") -%>">
          <td><%= link_to "#{customer.first_name} #{customer.last_name}", user_path(customer, view: 'customer') %></td>
          <td><%= total_book_count(customer) %></td>
          <td><%= current_checked_out_books(customer) %></td>
        </tr>
      <% end -%>
    </table>
  </div>
</div>

app/views/users/list.erb
<script type="module">
  import "controllers/import_books";
</script>

<div id="feature" class="floatLeft">
  <div id="featureHeading">
    <h1 class="floatLeft">Customer List</h1>
    <div class="clear"></div>
  </div>
  <div id="featureWrap" class="floatLeft reports">  
  	<table class="report" cellpadding="0" cellspacing="0">
  		<tr>
  			<th>Customer Name</th>
  			<th>Total Book Count</th>
        <th>Checked Out Count</th>
  		</tr>
  		<% @customers.each do |customer| -%>
  			<tr class="<%= cycle("rowA", "rowB") -%>">
          <td><%= link_to "#{customer.first_name} #{customer.last_name}", user_path(customer, view: 'librarian') %></td>
          <td><%= total_book_count(customer) %></td>
          <td><%= current_checked_out_books(customer) %></td>
        </tr>
      <% end -%>
    </table>
  </div>
  <div class="below-table">
    <%= link_to "Download Books Status",
                export_books_path,
                class: "btn",
                data: { turbo: false } %>
  </div>
  <div class="below-table">
    <%= render :partial => 'books/new' %>
  </div>
</div>

app/views/users/show.erb
<%= render partial: "show_as_#{params[:view]}" %> 